apiVersion: 1
datasources:
  - name: JSON API
    type: marcusolsson-json-datasource
    access: proxy
    url: http://api:8000
    isDefault: false
    uid: gpu-obs-json-api
    orgId: 1
    version: 1
    editable: false
